"use client";

import { motion } from "framer-motion";
import { FileText, Download } from "lucide-react";

interface StudySheetCardProps {
  title: string;
  fileSize: string;
  onDownload: () => void;
}

export function StudySheetCard({
  title,
  fileSize,
  onDownload,
}: StudySheetCardProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, ease: "easeOut" }}
      className="relative w-full max-w-[400px] rounded-xl overflow-hidden"
    >
      {/* Main Card with Glassmorphism */}
      <div className="relative bg-background/70 backdrop-blur-xl border-[0.5px] border-primary/60 rounded-xl p-4 overflow-hidden">
        {/* Cypher Logo Watermark */}
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          <svg
            viewBox="0 0 100 100"
            className="w-24 h-24 opacity-[0.06]"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            {/* Hexagonal border */}
            <path
              d="M50 5 L90 27.5 L90 72.5 L50 95 L10 72.5 L10 27.5 Z"
              stroke="currentColor"
              strokeWidth="2"
              className="text-primary"
              fill="none"
            />
            {/* Inner accent lines */}
            <path
              d="M50 15 L80 32.5 L80 67.5 L50 85 L20 67.5 L20 32.5 Z"
              stroke="currentColor"
              strokeWidth="1"
              className="text-primary"
              fill="none"
            />
            {/* C letter */}
            <text
              x="50"
              y="60"
              textAnchor="middle"
              className="text-primary fill-primary"
              fontSize="36"
              fontWeight="bold"
            >
              C
            </text>
          </svg>
          {/* Red glow behind logo */}
          <div className="absolute w-20 h-20 bg-primary/15 blur-2xl rounded-full" />
        </div>

        {/* Content */}
        <div className="relative z-10 flex items-start gap-3">
          {/* File Type Icon */}
          <div className="w-11 h-11 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
            <FileText className="w-5 h-5 text-primary" />
          </div>

          {/* File Info */}
          <div className="flex-1 min-w-0">
            <h3 className="font-semibold text-foreground truncate text-sm leading-tight">
              {title}
            </h3>
            <p className="text-xs text-muted-foreground mt-1">
              {fileSize} &middot; Generated by Cypher
            </p>
          </div>
        </div>

        {/* Download Button with Shimmer */}
        <motion.button
          onClick={onDownload}
          whileHover={{ scale: 1.01 }}
          whileTap={{ scale: 0.99 }}
          className="relative mt-4 w-full py-2.5 px-4 rounded-lg font-medium text-sm text-primary-foreground bg-primary overflow-hidden group"
        >
          {/* Shimmer Effect */}
          <motion.div
            className="absolute inset-0 bg-gradient-to-r from-transparent via-white/25 to-transparent -translate-x-full"
            animate={{ translateX: ["-100%", "200%"] }}
            transition={{
              duration: 2,
              repeat: Infinity,
              repeatDelay: 1.5,
              ease: "easeInOut",
            }}
          />
          
          {/* Outer Glow */}
          <div className="absolute inset-0 rounded-lg shadow-[0_0_12px_rgba(239,68,68,0.3)] group-hover:shadow-[0_0_18px_rgba(239,68,68,0.5)] transition-shadow duration-300" />
          
          <span className="relative z-10 flex items-center justify-center gap-2">
            <Download className="w-4 h-4" />
            Download Now
          </span>
        </motion.button>
      </div>
    </motion.div>
  );
}
